### ISSUE TITLE
2-5 D번 야전방에서 대파시 빨간색으로 경고가 뜨지 않음

### ISSUE THREAD

**Issue by neropsys** [FreyYa/KanColleViewer#18]
![k-231](https://cloud.githubusercontent.com/assets/4974667/8147767/f5d9a8fa-12b6-11e5-8df5-796fb6d391a2.png)

**Comment by FreyYa** [comment]
Fixed: https://github.com/FreyYa/BattleInfoPlugin/commit/80525652480d3c3656994c5a685ec9b98fde18e8

**Comment by FreyYa** [comment]
대파여부를 적용하는 부분이 빠져있었습니다
