### ISSUE TITLE
툴 탭의 BattleInfo에 있는 해역정보를 조회할때 프로그램이 멈춥니다.

### ISSUE THREAD

**Issue by neropsys** [FreyYa/KanColleViewer#19]
![k-352](https://cloud.githubusercontent.com/assets/4974667/8841014/bad605b0-3123-11e5-9d83-5e66f0646e79.png)

**Comment by FreyYa** [comment]
해당기능은 현재 API의 변경으로 인해 사용중지 해놓은 상태입니다. 되도록이면 해당 내용이 적용된 최신버전 사용을 권장합니다.
