### ISSUE TITLE
딱지와 표시가 맞지 않습니다

### ISSUE THREAD

**Issue by kanglib** [FreyYa/KanColleViewer#21]
https://github.com/FreyYa/KanColleViewer/blob/master/Grabacr07.KanColleViewer/Views/Catalogs/ShipCatalogWindow.xaml#L934

![1](https://cloud.githubusercontent.com/assets/10681724/9363172/d27aa0c8-46df-11e5-985f-f26a024a0dd8.png)

3분류인데 표시는 5분류로 나옵니다.

**Comment by FreyYa** [comment]
아 이런 실수를....금방 수정해서 다시 올리도록 하겠습니다

**Comment by FreyYa** [comment]
https://github.com/FreyYa/KanColleViewer/commit/7a83a8269027dcc77cea185c0bb315b5633ee36f
수정완료되었습니다. 정확한 제보 감사합니다
