### ISSUE TITLE
150908 translations

### ISSUE THREAD

**Issue by DaeWha** [FreyYa/KanColleViewer#22]
https://mega.nz/#!TlVDTZiQ!wkuDSkTdwIbWxM6RRXOZO2O55YTNcN6wRczUga-N9Ig

신규 임무 중 항모기동부대, 북방해역에 진출하라! 의 경우는 아직 임무창에 띄우질 못해서 퀘스트 넘버가 맞는지 모르겠음

**Comment by FreyYa** [comment]
번역자료 제공 감사합니다
