### ISSUE TITLE
방금 전 업데이트 된 칸코레 뷰어에서 오류가 발생합니다

### ISSUE THREAD

**Issue by toaru1234** [FreyYa/KanColleViewer#27]
error.log 내용입니다. Autoupdater.exe로 자동 업데이트했습니다.

ERROR, date = 2015-12-17 오후 11:25:47 +09:00, sender = 이름:KanColleViewer.exe
컨텍스트 정책이 없습니다.
,
System.MissingMethodException: 메서드를 찾을 수 없습니다. 'Boolean Grabacr07.KanColleWrapper.IKanColleClientSettings.get_SqrtDoubleToInt()'
   위치: Grabacr07.KanColleViewer.Application.OnStartup(StartupEventArgs e)
   위치: System.Windows.Application.<_ctor>b__0(Object unused)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   위치: System.Windows.Threading.DispatcherOperation.InvokeImpl()
   위치: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   위치: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   위치: System.Windows.Threading.DispatcherOperation.Invoke()
   위치: System.Windows.Threading.Dispatcher.ProcessQueue()
   위치: System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   위치: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   위치: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   위치: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   위치: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   위치: MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   위치: System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   위치: System.Windows.Application.RunDispatcher(Object ignore)
   위치: System.Windows.Application.RunInternal(Window window)
   위치: Grabacr07.KanColleViewer.Application.Main()

**Comment by FreyYa** [comment]
제보 감사합니다. 방금 오류를 확인하였으니 문제 조치후 바로 갱신하도록하겠습니다

**Comment by FreyYa** [comment]
수정 완료되었습니다. 현재 업데이트 된 상태이고 블로그에서 수동 업데이트를 하셔도 됩니다
