### ISSUE TITLE
기능추가에 대한 건의

### ISSUE THREAD

**Issue by tony9959** [FreyYa/KanColleViewer#8]
노트뷱이나 윈도우 태블릿같은 저사양기기들로 허다보면 약간씩 끊기는데, 영어판 뷰어를 보면 설정에 플래시 설정이 있는데 플래시를 다이렉트 윈도우로 해놓으면 렉이많이 줄어든다. 이기능 한글판에도 추가해줄수 있음? 노트북을살..

**Comment by DaeWha** [comment]
탭이 너무 많다면 다른탭에 비해 상대적으로 활용도가 떨어지는 툴탭을 프리뷰탭으로 대체하거나 프리뷰탭을 툴팁 세부탭에 넣을 수 있을것 같다.
그리고 2-5 야전방에 등장하는 중순리급改의 번역이 되어있지 않다.

**Comment by FreyYa** [comment]
플래시쪽은 일단 전투예보가 끝나면 추가고려 해보겠습니다. 예보를 아예 툴 탭 아래에 넣는것도 좋은 방법일듯합니다. 지금은 보기가 꽤 귀찮은 구조이기때문에...심해서함 번역 안된거 있으면 ships.xml파일의 심해서함 부분을 별도로 적어서 답변 달아주시면 감사하겠습니다.

**Comment by DaeWha** [comment]
깡갤 머화왕한대화인데 지난번에 Quests에 반영 안된 원양잠수함작전,2차 원양잠수함작전 오류 수정이랑 Ships쪽에 중순리급改
수정해서 넣어줬음

**Comment by FreyYa** [comment]
정확히 어디에 올렸는지 알려주면 감사하겠슴. 그리고 언제나 수고하심

**Comment by DaeWha** [comment]
gmail로 알림이 오길래 이게 gmail 통한 메일인줄알고 답장으로 보냈는데 걍 자체적으로 달려있는 기능이네. 네이버 메일로 보내드리겠음
